INSERT INTO UF (NOME, SIGLA) VALUES ('Acre',                  'AC');
INSERT INTO UF (NOME, SIGLA) VALUES ('Alagoas',               'AL');
INSERT INTO UF (NOME, SIGLA) VALUES ('Amapá',                 'AP');
INSERT INTO UF (NOME, SIGLA) VALUES ('Amazonas',              'AM');
INSERT INTO UF (NOME, SIGLA) VALUES ('Bahia',                 'BA');
INSERT INTO UF (NOME, SIGLA) VALUES ('Ceará',                 'CE');
INSERT INTO UF (NOME, SIGLA) VALUES ('Distrito Federal',      'DF');
INSERT INTO UF (NOME, SIGLA) VALUES ('Espírito Santo',        'ES');
INSERT INTO UF (NOME, SIGLA) VALUES ('Goiás',                 'GO');
INSERT INTO UF (NOME, SIGLA) VALUES ('Maranhão',              'MA');
INSERT INTO UF (NOME, SIGLA) VALUES ('Mato Grosso do Sul',    'MS');
INSERT INTO UF (NOME, SIGLA) VALUES ('Mato Grosso',           'MT');
INSERT INTO UF (NOME, SIGLA) VALUES ('Minas Gerais',          'MG');
INSERT INTO UF (NOME, SIGLA) VALUES ('Paraná',                'PR');
INSERT INTO UF (NOME, SIGLA) VALUES ('Paraíba',               'PB');
INSERT INTO UF (NOME, SIGLA) VALUES ('Pará',                  'PA');
INSERT INTO UF (NOME, SIGLA) VALUES ('Pernambuco',            'PE');
INSERT INTO UF (NOME, SIGLA) VALUES ('Piauí',                 'PI');
INSERT INTO UF (NOME, SIGLA) VALUES ('Rio de Janeiro',        'RJ');
INSERT INTO UF (NOME, SIGLA) VALUES ('Rio Grande do Norte',   'RN');
INSERT INTO UF (NOME, SIGLA) VALUES ('Rio Grande do Sul (*)', 'RS');
INSERT INTO UF (NOME, SIGLA) VALUES ('Rondônia',              'RO');
INSERT INTO UF (NOME, SIGLA) VALUES ('Roraima',               'RR');
INSERT INTO UF (NOME, SIGLA) VALUES ('Santa Catarina',        'SC');
INSERT INTO UF (NOME, SIGLA) VALUES ('Sergipe',               'SE');
INSERT INTO UF (NOME, SIGLA) VALUES ('São Paulo',             'SP');
INSERT INTO UF (NOME, SIGLA) VALUES ('Tocantins',             'TO');

INSERT INTO USUARIO (LOGIN, SENHA, PERFIL) VALUES ('adm', '376e7fa916ed8d7068ddceadc1252e15d6ee7085', 'ADMINISTRADOR');
INSERT INTO USUARIO (LOGIN, SENHA, PERFIL) VALUES ('rel', '376e7fa916ed8d7068ddceadc1252e15d6ee7085', 'RELATOR');